cmake_minimum_required(VERSION 3.21)
find_package(Git REQUIRED)
if(NOT DEFINED TEST_ROOT OR NOT DEFINED SOURCE_DIR)
    message(FATAL_ERROR "TEST_ROOT and SOURCE_DIR are required")
endif()
# Never mutate the user's checkout or reuse a previous run's Git history.
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef run_id)
set(fixture "${TEST_ROOT}/${run_id}/source")
set(identity_dir "${TEST_ROOT}/${run_id}/identity")
file(MAKE_DIRECTORY "${fixture}")
set(ROLLNW_SOURCE_DIR "${fixture}")
include("${SOURCE_DIR}/cmake/BuildIdentity.cmake")
foreach(directory IN LISTS ROLLNW_TOOL_DIRECTORIES)
    file(MAKE_DIRECTORY "${fixture}/tools/${directory}")
    file(WRITE "${fixture}/tools/${directory}/VERSION" "0.1.0\n")
endforeach()
file(MAKE_DIRECTORY "${fixture}/tools/vscode-smalls")
file(WRITE "${fixture}/tools/vscode-smalls/package.json" "{\"version\":\"0.0.2\"}\n")
file(WRITE "${fixture}/release.json" "{\"schema\":1,\"tag\":\"\",\"tools\":{}}\n")
file(WRITE "${fixture}/probe.cpp" [=[
#include "rollnw_tool_version.hpp"
#include <cstdio>
#include <cstring>
int main(int argc, char** argv) {
    if (argc == 2 && std::strcmp(argv[1], "--build-info") == 0) {
        std::puts(ROLLNW_TOOL_BUILD_INFO);
    } else {
        std::puts(ROLLNW_TOOL_NAME " " ROLLNW_TOOL_VERSION);
    }
}
]=])
set(probe_cmake [=[
cmake_minimum_required(VERSION 3.21)
project(identity_probes LANGUAGES CXX)
set(ROLLNW_BUILD_TOOLS ON)
include("@SOURCE_DIR@/cmake/ToolVersions.cmake")
foreach(tool IN LISTS ROLLNW_VERSIONED_TOOLS)
    add_executable(${tool} probe.cpp)
    rollnw_use_tool_version(${tool})
    install(TARGETS ${tool} RUNTIME DESTINATION bin)
endforeach()
]=])
string(CONFIGURE "${probe_cmake}" probe_cmake @ONLY)
file(WRITE "${fixture}/CMakeLists.txt" "${probe_cmake}")
set(probe_build "${TEST_ROOT}/${run_id}/build")
set(probe_package "${TEST_ROOT}/${run_id}/package")

function(run_ok)
    execute_process(COMMAND ${ARGV} RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT result STREQUAL "0")
        message(FATAL_ERROR "Command failed: ${ARGV}\n${output}\n${error}")
    endif()
endfunction()

function(generate tag expected_error)
    execute_process(COMMAND "${CMAKE_COMMAND}"
        "-DROLLNW_SOURCE_DIR=${fixture}" "-DROLLNW_IDENTITY_DIR=${identity_dir}"
        "-DROLLNW_RELEASE_TAG=${tag}" -P "${SOURCE_DIR}/cmake/BuildIdentity.cmake"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(expected_error STREQUAL "")
        if(NOT result STREQUAL "0")
            message(FATAL_ERROR "Identity generation failed: ${error}")
        endif()
    elseif(result STREQUAL "0" OR NOT error MATCHES "${expected_error}")
        message(FATAL_ERROR "Expected '${expected_error}', got status=${result}: ${error}")
    endif()
endfunction()

function(expect_field expected)
    file(READ "${identity_dir}/build-identity.json" identity)
    string(JSON actual GET "${identity}" ${ARGN})
    if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "${ARGN}: expected '${expected}', got '${actual}'")
    endif()
endfunction()

function(commit_fixture message)
    run_ok("${GIT_EXECUTABLE}" -C "${fixture}" add .)
    run_ok("${GIT_EXECUTABLE}" -C "${fixture}" -c commit.gpgsign=false commit -qm "${message}")
endfunction()

function(prepare tag tools expected_error)
    execute_process(COMMAND "${CMAKE_COMMAND}" "-DROLLNW_SOURCE_DIR=${fixture}"
        "-DROLLNW_RELEASE_TAG=${tag}" "-DROLLNW_RELEASE_TOOLS=${tools}"
        -P "${SOURCE_DIR}/scripts/ci/prepare_release.cmake"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(expected_error STREQUAL "")
        if(NOT result STREQUAL "0")
            message(FATAL_ERROR "Preparation failed: ${error}")
        endif()
    elseif(result STREQUAL "0" OR NOT error MATCHES "${expected_error}")
        message(FATAL_ERROR "Expected preparation error '${expected_error}': ${result}, ${error}")
    endif()
endfunction()

generate("" "")
expect_field(unknown revision)
expect_field("0.1.0-dev+unknown" tools mudl version)
generate("2026.09.08" "clean Git checkout")
foreach(invalid "0.1.0-dev" "01.1.0" "1.2" "1.2.3.4" "65536.0.0" "999999999999999999999.0.0")
    file(WRITE "${fixture}/tools/mudl/VERSION" "${invalid}\n")
    generate("" "numeric MAJOR.MINOR.PATCH|Version components")
endforeach()
file(WRITE "${fixture}/tools/mudl/VERSION" "65535.65535.65535\n")
generate("" "")
file(WRITE "${fixture}/tools/mudl/VERSION" "0.1.0\n")

run_ok("${GIT_EXECUTABLE}" -C "${fixture}" init -q -b main)
run_ok("${GIT_EXECUTABLE}" -C "${fixture}" config user.name "Build identity tests")
run_ok("${GIT_EXECUTABLE}" -C "${fixture}" config user.email "build-tests@example.invalid")
run_ok("${GIT_EXECUTABLE}" -C "${fixture}" config core.hooksPath "${fixture}/no-hooks")
commit_fixture(initial)
run_ok("${CMAKE_COMMAND}" -S "${fixture}" -B "${probe_build}" -G Ninja)
run_ok("${CMAKE_COMMAND}" --build "${probe_build}" --target mudl)
if(CMAKE_HOST_WIN32)
    set(probe_suffix .exe)
else()
    set(probe_suffix "")
endif()
run_ok("${CMAKE_COMMAND}" "-DTOOL=${probe_build}/mudl${probe_suffix}"
    "-DHEADER=${probe_build}/tool_versions/mudl/rollnw_tool_version.hpp"
    -P "${SOURCE_DIR}/tests/tool_version.cmake")
execute_process(COMMAND "${CMAKE_COMMAND}" --build "${probe_build}" --target mudl
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT result EQUAL 0 OR output MATCHES "Building CXX|Linking CXX")
    message(FATAL_ERROR "Unchanged build recompiled or failed: ${output}\n${error}")
endif()
generate("" "")
expect_field(clean source_state)
expect_field(development tools mudl channel)
file(TIMESTAMP "${identity_dir}/mudl/rollnw_tool_version.hpp" original_mtime "%s")
generate("" "")
file(TIMESTAMP "${identity_dir}/mudl/rollnw_tool_version.hpp" repeat_mtime "%s")
if(NOT original_mtime STREQUAL repeat_mtime)
    message(FATAL_ERROR "Unchanged identity rewrote the header")
endif()
file(WRITE "${fixture}/untracked.txt" "source change\n")
run_ok("${CMAKE_COMMAND}" --build "${probe_build}" --target mudl)
execute_process(COMMAND "${probe_build}/mudl${probe_suffix}" --build-info
    OUTPUT_VARIABLE probe_identity COMMAND_ERROR_IS_FATAL ANY)
string(JSON probe_state GET "${probe_identity}" source_state)
if(NOT probe_state STREQUAL "dirty")
    message(FATAL_ERROR "Incremental build did not refresh dirty identity")
endif()
generate("" "")
expect_field(dirty source_state)
generate("2026.09.08" "clean Git checkout")
commit_fixture(change)
foreach(invalid "2026.02.29" "2026.04.31" "2026.09.08.1" "2026-09-08" "2026.13.01" "v1.0.0")
    prepare("${invalid}" "mudl" "calendar date|Expected YYYY")
endforeach()
prepare("2028.02.29" "mudl" "")
prepare("2026.09.08.2" "mudl" "")
prepare("2026.09.08" "not-a-tool" "Unknown or duplicate")
prepare("2026.09.08" "mudl;mudl" "Unknown or duplicate")
prepare("vscode-smalls/0.0.3" "smalls-lsp" "match package.json")
prepare("vscode-smalls/0.0.2" "mudl" "exactly smalls-lsp")
prepare("2026.09.07" "" "")
commit_fixture(snapshot_only)
run_ok("${GIT_EXECUTABLE}" -C "${fixture}" tag 2026.09.07)
generate("2026.09.07" "")
expect_field(development tools mudl channel)
expect_field("2026.09.07" snapshot)
prepare("2026.09.08" "mudl;rollnw-client" "")
commit_fixture(release)
generate("2026.09.08" "Git identity check failed")
run_ok("${GIT_EXECUTABLE}" -C "${fixture}" -c tag.gpgsign=false tag -a 2026.09.08 -m release)
run_ok("${CMAKE_COMMAND}" -S "${fixture}" -B "${probe_build}" -DROLLNW_RELEASE_TAG=2026.09.08)
run_ok("${CMAKE_COMMAND}" --build "${probe_build}")
run_ok("${CMAKE_COMMAND}" --install "${probe_build}" --prefix "${probe_package}")
# Do not pass the list through run_ok's variadic arguments: retain it as one -D.
execute_process(COMMAND "${CMAKE_COMMAND}" "-DPACKAGE_ROOT=${probe_package}"
    "-DTOOLS=${ROLLNW_VERSIONED_TOOLS}" -P "${SOURCE_DIR}/scripts/ci/validate_tool_packages.cmake"
    COMMAND_ERROR_IS_FATAL ANY)
file(READ "${probe_package}/build-identity.json" package_identity)
foreach(field version revision)
    string(JSON tampered SET "${package_identity}" tools mudl "${field}" "\"wrong\"")
    file(WRITE "${probe_package}/build-identity.json" "${tampered}\n")
    execute_process(COMMAND "${CMAKE_COMMAND}" "-DPACKAGE_ROOT=${probe_package}"
        -DTOOLS=mudl -P "${SOURCE_DIR}/scripts/ci/validate_tool_packages.cmake"
        RESULT_VARIABLE result OUTPUT_QUIET ERROR_VARIABLE error)
    if(result STREQUAL "0" OR NOT error MATCHES "packaged .* mismatch")
        message(FATAL_ERROR "Package validator missed altered ${field}: ${error}")
    endif()
endforeach()
file(WRITE "${probe_package}/build-identity.json" "${package_identity}")
generate("2026.09.08" "")
expect_field("0.1.0" tools mudl version)
expect_field(release tools rollnw-client channel)
expect_field(development tools smalls channel)
expect_field("2026.09.08" snapshot)
file(READ "${identity_dir}/mudl/tool_version.rc" resource)
if(NOT resource MATCHES "FILEFLAGS 0x0L")
    message(FATAL_ERROR "Approved Windows resource is marked prerelease")
endif()
generate("" "") # Merely being at a release tag never promotes tools.
expect_field(development tools mudl channel)
prepare("2026.09.08" "mudl" "already exists")
prepare("2026.09.09" "mudl" "must exceed")
file(WRITE "${fixture}/tools/mudl/VERSION" "0.1.1\n")
generate("2026.09.08" "clean Git checkout")
commit_fixture(next_version)
generate("2026.09.08" "must point at")
run_ok("${GIT_EXECUTABLE}" -C "${fixture}" tag 2026.09.09)
generate("2026.09.09" "does not match requested")

# Validate manifest shape, exact tool versions, and unknown names separately
# from checkout integrity. Each fixture tag points at its own clean commit.
set(bad_manifests
    "{\"schema\":2,\"tag\":\"2026.09.10\",\"tools\":{}}"
    "{\"schema\":1,\"tag\":\"2026.09.11\",\"tools\":{\"mudl\":\"8.0.0\"}}"
    "{\"schema\":1,\"tag\":\"2026.09.12\",\"tools\":{\"unknown\":\"0.1.0\"}}")
foreach(manifest IN LISTS bad_manifests)
    string(JSON tag GET "${manifest}" tag)
    file(WRITE "${fixture}/release.json" "${manifest}\n")
    commit_fixture(bad_manifest)
    run_ok("${GIT_EXECUTABLE}" -C "${fixture}" tag "${tag}")
    generate("${tag}" "expected schema 1|unknown tool or VERSION mismatch")
endforeach()
prepare("vscode-smalls/0.0.2" "smalls-lsp" "")
commit_fixture(extension)
run_ok("${GIT_EXECUTABLE}" -C "${fixture}" tag vscode-smalls/0.0.2)
generate("vscode-smalls/0.0.2" "")
expect_field(release tools smalls-lsp channel)
expect_field(development tools mudl channel)
expect_field("" snapshot)
expect_field("0.0.2" extension_version)

# A later release must not prevent reproducing the earlier tagged source.
run_ok("${GIT_EXECUTABLE}" -C "${fixture}" checkout -q --detach 2026.09.08)
generate("2026.09.08" "")
expect_field(release tools mudl channel)

set(worktree "${TEST_ROOT}/${run_id}/worktree")
run_ok("${GIT_EXECUTABLE}" -C "${fixture}" worktree add -q --detach "${worktree}" 2026.09.08)
set(primary_fixture "${fixture}")
set(fixture "${worktree}")
generate("2026.09.08" "")
expect_field(clean source_state)
expect_field(release tools mudl channel)
set(fixture "${primary_fixture}")

set(shallow "${TEST_ROOT}/${run_id}/shallow")
if(CMAKE_HOST_WIN32)
    set(fixture_uri "file:///${fixture}")
else()
    set(fixture_uri "file://${fixture}")
endif()
run_ok("${GIT_EXECUTABLE}" clone -q --depth=1 --branch 2026.09.08 "${fixture_uri}" "${shallow}")
set(fixture "${shallow}")
generate("2026.09.08" "full history and tags")
message(STATUS "Build identity archive, version, dirty, tag, approval, history, and extension checks passed")
