if(NOT DEFINED ROLLNW_TEST_TMP_DIR OR ROLLNW_TEST_TMP_DIR STREQUAL "")
    message(FATAL_ERROR "ROLLNW_TEST_TMP_DIR is required")
endif()

file(REMOVE_RECURSE "${ROLLNW_TEST_TMP_DIR}")
file(MAKE_DIRECTORY "${ROLLNW_TEST_TMP_DIR}")
