file(READ "${HEADER}" metadata)
string(REGEX MATCH "#define ROLLNW_TOOL_NAME \"([^\"]+)\"" match "${metadata}")
set(tool_name "${CMAKE_MATCH_1}")
string(REGEX MATCH "#define ROLLNW_TOOL_VERSION \"([^\"]+)\"" match "${metadata}")
set(tool_version "${CMAKE_MATCH_1}")
if(tool_name STREQUAL "" OR tool_version STREQUAL "")
    message(FATAL_ERROR "Invalid generated tool metadata: ${HEADER}")
endif()
string(REGEX MATCH "#define ROLLNW_TOOL_BUILD_INFO R\"rollnw\\(([^\n]+)\\)rollnw\"" match "${metadata}")
string(JSON expected GET "${CMAKE_MATCH_1}")
execute_process(COMMAND "${TOOL}" --build-info
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 10)
if(NOT result STREQUAL "0" OR NOT error STREQUAL "")
    message(FATAL_ERROR "--build-info failed: status=${result}, stderr='${error}'")
endif()
string(JSON actual GET "${output}")
if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "--build-info differs from compiled metadata")
endif()
execute_process(COMMAND "${TOOL}" --version
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 10)
string(STRIP "${output}" output)
if(NOT result STREQUAL "0" OR NOT output STREQUAL "${tool_name} ${tool_version}" OR NOT error STREQUAL "")
    message(FATAL_ERROR "--version failed: status=${result}, stdout='${output}', stderr='${error}'")
endif()
