cmake_minimum_required(VERSION 3.21)
if(NOT DEFINED ROLLNW_SOURCE_DIR)
    get_filename_component(ROLLNW_SOURCE_DIR "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
endif()
include("${CMAKE_CURRENT_LIST_DIR}/../../cmake/BuildIdentity.cmake")
if(NOT DEFINED ROLLNW_RELEASE_TAG OR NOT DEFINED ROLLNW_RELEASE_TOOLS)
    message(FATAL_ERROR "Supply -DROLLNW_RELEASE_TAG=tag and -DROLLNW_RELEASE_TOOLS=tool1;tool2 (empty for snapshot only)")
endif()
rollnw_check_release_tag("${ROLLNW_RELEASE_TAG}")
rollnw_read_tool_versions()
find_package(Git REQUIRED)
rollnw_git(shallow rev-parse --is-shallow-repository)
if(shallow STREQUAL "true")
    message(FATAL_ERROR "Release preparation requires full history and tags")
endif()
execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${ROLLNW_SOURCE_DIR}"
    show-ref --verify --quiet "refs/tags/${ROLLNW_RELEASE_TAG}" RESULT_VARIABLE tag_exists)
if(tag_exists EQUAL 0)
    message(FATAL_ERROR "Release tag already exists; do not move or replace released tags")
endif()
set(approvals "{}")
set(seen "")
foreach(tool IN LISTS ROLLNW_RELEASE_TOOLS)
    if(NOT tool IN_LIST ROLLNW_VERSIONED_TOOLS OR tool IN_LIST seen)
        message(FATAL_ERROR "Unknown or duplicate release tool: '${tool}'")
    endif()
    list(APPEND seen "${tool}")
    string(JSON approvals SET "${approvals}" "${tool}" "\"${ROLLNW_VERSION_${tool}}\"")
endforeach()
if(ROLLNW_RELEASE_TAG MATCHES "^vscode-smalls/" AND NOT seen STREQUAL "smalls-lsp")
    message(FATAL_ERROR "Extension releases must approve exactly smalls-lsp")
endif()
rollnw_check_release_versions("${approvals}")
set(manifest "{\"schema\":1,\"tag\":\"${ROLLNW_RELEASE_TAG}\",\"tools\":${approvals}}")
string(JSON manifest GET "${manifest}")
file(CONFIGURE OUTPUT "${ROLLNW_SOURCE_DIR}/release.json" CONTENT "${manifest}\n" @ONLY)
message(STATUS "Prepared release.json. Review and commit it with the selected VERSION files before tagging. No tag was created.")
