cmake_minimum_required(VERSION 3.21)
# Batch contract: explicit tool names + package root -> exact identity checks on
# installed executables. No discovery by filename or dependency on game assets.
if(NOT DEFINED PACKAGE_ROOT OR NOT DEFINED TOOLS OR TOOLS STREQUAL "")
    message(FATAL_ERROR "Supply PACKAGE_ROOT and a nonempty TOOLS list")
endif()
file(READ "${PACKAGE_ROOT}/build-identity.json" metadata)
foreach(tool IN LISTS TOOLS)
    string(JSON expected GET "${metadata}" tools "${tool}")
    string(JSON version GET "${expected}" version)
    set(executable "${PACKAGE_ROOT}/bin/${tool}${CMAKE_EXECUTABLE_SUFFIX}")
    # CMAKE_EXECUTABLE_SUFFIX is unset in script mode on Windows.
    if(CMAKE_HOST_WIN32)
        set(executable "${PACKAGE_ROOT}/bin/${tool}.exe")
    endif()
    foreach(option --version --build-info)
        execute_process(COMMAND "${executable}" "${option}"
            RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 10)
        string(STRIP "${output}" output)
        if(NOT result STREQUAL "0" OR NOT error STREQUAL "")
            message(FATAL_ERROR "${tool} ${option} failed: status=${result}, stderr='${error}'")
        endif()
        if(option STREQUAL "--version")
            if(NOT output STREQUAL "${tool} ${version}")
                message(FATAL_ERROR "${tool}: packaged version mismatch: '${output}'")
            endif()
        else()
            string(JSON actual GET "${output}")
            if(NOT actual STREQUAL expected)
                message(FATAL_ERROR "${tool}: packaged build identity mismatch")
            endif()
        endif()
    endforeach()
    message(STATUS "Verified packaged ${tool} ${version}")
endforeach()
