# Shared by configuration, the build-time refresh, and release preparation.
# Contract: five numeric VERSION files + one checkout + one optional approval
# manifest -> build-owned, immutable tool identities. No runtime Git dependency.
if(CMAKE_SCRIPT_MODE_FILE STREQUAL CMAKE_CURRENT_LIST_FILE)
    cmake_minimum_required(VERSION 3.21)
endif()
set(ROLLNW_VERSIONED_TOOLS rollnw-client mudl smalls smalls-lsp smalls-datagen)
set(ROLLNW_TOOL_DIRECTORIES client mudl smalls smalls-lsp smalls-datagen)

function(rollnw_check_numeric_version version)
    if(NOT "${version}" MATCHES "^([0-9]+)\\.([0-9]+)\\.([0-9]+)$")
        message(FATAL_ERROR "Expected numeric MAJOR.MINOR.PATCH, got '${version}'")
    endif()
    foreach(component "${CMAKE_MATCH_1}" "${CMAKE_MATCH_2}" "${CMAKE_MATCH_3}")
        string(LENGTH "${component}" length)
        if(length GREATER 5 OR component GREATER 65535 OR component MATCHES "^0[0-9]")
            message(FATAL_ERROR "Version components must be 0..65535 without leading zeroes: '${version}'")
        endif()
    endforeach()
endfunction()

function(rollnw_read_tool_versions)
    foreach(index RANGE 0 4)
        list(GET ROLLNW_VERSIONED_TOOLS ${index} tool)
        list(GET ROLLNW_TOOL_DIRECTORIES ${index} directory)
        file(READ "${ROLLNW_SOURCE_DIR}/tools/${directory}/VERSION" version)
        string(STRIP "${version}" version)
        rollnw_check_numeric_version("${version}")
        set("ROLLNW_VERSION_${tool}" "${version}" PARENT_SCOPE)
    endforeach()
endfunction()

# One release tag selects one distribution or extension package (a singleton).
function(rollnw_check_release_tag tag)
    if(tag MATCHES "^vscode-smalls/([0-9]+\\.[0-9]+\\.[0-9]+)$")
        rollnw_check_numeric_version("${CMAKE_MATCH_1}")
        file(READ "${ROLLNW_SOURCE_DIR}/tools/vscode-smalls/package.json" extension)
        string(JSON extension_version GET "${extension}" version)
        if(NOT tag STREQUAL "vscode-smalls/${extension_version}")
            message(FATAL_ERROR "Extension release tag must match package.json version")
        endif()
        return()
    endif()
    if(NOT tag MATCHES "^(20[0-9][0-9])\\.(0[1-9]|1[0-2])\\.(0[1-9]|[12][0-9]|3[01])(\\.([2-9]|[1-9][0-9]+))?$")
        message(FATAL_ERROR "Expected YYYY.MM.DD[.N] (N >= 2) or vscode-smalls/MAJOR.MINOR.PATCH")
    endif()
    set(year "${CMAKE_MATCH_1}")
    set(month "${CMAKE_MATCH_2}")
    set(day "${CMAKE_MATCH_3}")
    string(REGEX REPLACE "^0" "" month "${month}")
    string(REGEX REPLACE "^0" "" day "${day}")
    set(days 31 28 31 30 31 30 31 31 30 31 30 31)
    math(EXPR leap "${year} % 4") # Accepted years are 2000..2099.
    if(month EQUAL 2 AND leap EQUAL 0)
        set(limit 29)
    else()
        math(EXPR index "${month} - 1")
        list(GET days ${index} limit)
    endif()
    if(day GREATER limit)
        message(FATAL_ERROR "Release tag is not a calendar date: '${tag}'")
    endif()
endfunction()

function(rollnw_git output)
    execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${ROLLNW_SOURCE_DIR}" ${ARGN}
        RESULT_VARIABLE result OUTPUT_VARIABLE value ERROR_VARIABLE error
        OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Git identity check failed: ${error}")
    endif()
    set(${output} "${value}" PARENT_SCOPE)
endfunction()

function(rollnw_read_release_approvals output)
    file(READ "${ROLLNW_SOURCE_DIR}/release.json" manifest)
    string(JSON schema GET "${manifest}" schema)
    string(JSON tag GET "${manifest}" tag)
    string(JSON approvals GET "${manifest}" tools)
    string(JSON count LENGTH "${manifest}")
    string(JSON schema_type TYPE "${manifest}" schema)
    string(JSON tag_type TYPE "${manifest}" tag)
    string(JSON tools_type TYPE "${manifest}" tools)
    if(NOT schema_type STREQUAL "NUMBER" OR NOT schema EQUAL 1 OR NOT count EQUAL 3
        OR NOT tag_type STREQUAL "STRING" OR NOT tools_type STREQUAL "OBJECT")
        message(FATAL_ERROR "release.json: expected schema 1, tag string, and tools object only")
    endif()
    if(NOT tag STREQUAL ROLLNW_RELEASE_TAG)
        message(FATAL_ERROR "release.json tag '${tag}' does not match requested '${ROLLNW_RELEASE_TAG}'")
    endif()
    string(JSON count LENGTH "${approvals}")
    if(count GREATER 0)
        math(EXPR last "${count} - 1")
        foreach(index RANGE 0 ${last})
            string(JSON tool MEMBER "${approvals}" ${index})
            string(JSON version GET "${approvals}" "${tool}")
            string(JSON type TYPE "${approvals}" "${tool}")
            if(NOT tool IN_LIST ROLLNW_VERSIONED_TOOLS OR NOT type STREQUAL "STRING"
                OR NOT version STREQUAL "${ROLLNW_VERSION_${tool}}")
                message(FATAL_ERROR "release.json: unknown tool or VERSION mismatch for '${tool}'")
            endif()
        endforeach()
    endif()
    if(ROLLNW_RELEASE_TAG MATCHES "^vscode-smalls/")
        string(JSON lsp ERROR_VARIABLE missing GET "${approvals}" smalls-lsp)
        if(missing OR NOT count EQUAL 1)
            message(FATAL_ERROR "Extension releases must approve exactly smalls-lsp")
        endif()
    endif()
    set(${output} "${approvals}" PARENT_SCOPE)
endfunction()

# Validate only ancestor releases: future tags must not prevent rebuilding an
# older release. Conservatively require a bump for each newly approved tool;
# shared library changes also change tool builds.
function(rollnw_check_release_versions approvals)
    rollnw_git(refs for-each-ref --merged=HEAD "--format=%(refname)" refs/tags)
    string(REPLACE "\n" ";" refs "${refs}")
    foreach(ref IN LISTS refs)
        if(ref STREQUAL "refs/tags/${ROLLNW_RELEASE_TAG}")
            continue()
        endif()
        execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${ROLLNW_SOURCE_DIR}"
            show "${ref}:release.json" RESULT_VARIABLE result OUTPUT_VARIABLE previous ERROR_QUIET)
        if(NOT result EQUAL 0)
            continue() # Tags from before this release policy have no manifest.
        endif()
        string(JSON previous_tag ERROR_VARIABLE error GET "${previous}" tag)
        if(error OR NOT ref STREQUAL "refs/tags/${previous_tag}")
            continue() # Unrelated tags do not constitute release approvals.
        endif()
        foreach(tool IN LISTS ROLLNW_VERSIONED_TOOLS)
            string(JSON version ERROR_VARIABLE missing GET "${approvals}" "${tool}")
            string(JSON prior ERROR_VARIABLE not_released GET "${previous}" tools "${tool}")
            if(NOT missing AND NOT not_released)
                rollnw_check_numeric_version("${prior}")
                if(version VERSION_LESS_EQUAL prior)
                    message(FATAL_ERROR "${tool} ${version} must exceed ${prior} approved by ${previous_tag}")
                endif()
            endif()
        endforeach()
    endforeach()
endfunction()

function(rollnw_generate_tool_versions)
    rollnw_read_tool_versions()
    set(revision unknown)
    set(source_state unknown)
    set(snapshot "")
    set(approvals "{}")
    find_package(Git QUIET)
    # Do not accidentally identify an enclosing repository for source archives.
    if(GIT_FOUND AND EXISTS "${ROLLNW_SOURCE_DIR}/.git")
        rollnw_git(revision rev-parse --verify HEAD)
        rollnw_git(status status --porcelain --untracked-files=normal --ignore-submodules=none)
        set(source_state clean)
        if(NOT status STREQUAL "")
            set(source_state dirty)
        endif()
    endif()
    if(NOT revision STREQUAL "unknown" AND NOT revision MATCHES "^[0-9a-f]+$")
        message(FATAL_ERROR "Invalid Git revision")
    endif()
    if(NOT "${ROLLNW_RELEASE_TAG}" STREQUAL "")
        rollnw_check_release_tag("${ROLLNW_RELEASE_TAG}")
        if(NOT source_state STREQUAL "clean")
            message(FATAL_ERROR "Release builds require a clean Git checkout, including untracked files")
        endif()
        rollnw_git(shallow rev-parse --is-shallow-repository)
        if(shallow STREQUAL "true")
            message(FATAL_ERROR "Release validation requires full history and tags (fetch-depth: 0)")
        endif()
        rollnw_git(tag_revision rev-parse --verify "refs/tags/${ROLLNW_RELEASE_TAG}^{commit}")
        if(NOT tag_revision STREQUAL revision)
            message(FATAL_ERROR "Release tag must point at the checked-out revision")
        endif()
        rollnw_read_release_approvals(approvals)
        rollnw_check_release_versions("${approvals}")
        if(NOT ROLLNW_RELEASE_TAG MATCHES "^vscode-smalls/")
            set(snapshot "${ROLLNW_RELEASE_TAG}")
        endif()
    endif()
    string(SUBSTRING "${revision}" 0 12 short_revision)
    set(suffix "-dev+g${short_revision}")
    if(revision STREQUAL "unknown")
        set(suffix "-dev+unknown")
    elseif(source_state STREQUAL "dirty")
        string(APPEND suffix ".dirty")
    endif()
    set(build_identity "{\"schema\":1,\"revision\":\"${revision}\",\"source_state\":\"${source_state}\",\"release_tag\":\"${ROLLNW_RELEASE_TAG}\",\"snapshot\":\"${snapshot}\",\"tools\":{}}")
    foreach(tool_name IN LISTS ROLLNW_VERSIONED_TOOLS)
        set(base_version "${ROLLNW_VERSION_${tool_name}}")
        set(tool_version "${base_version}${suffix}")
        set(channel development)
        set(version_flags "0x2L") # VS_FF_PRERELEASE
        string(JSON approved ERROR_VARIABLE not_approved GET "${approvals}" "${tool_name}")
        if(NOT not_approved)
            set(tool_version "${base_version}")
            set(channel release)
            set(version_flags "0x0L")
        endif()
        set(tool_build_info "{\"schema\":1,\"tool\":\"${tool_name}\",\"base_version\":\"${base_version}\",\"version\":\"${tool_version}\",\"channel\":\"${channel}\",\"revision\":\"${revision}\",\"source_state\":\"${source_state}\",\"release_tag\":\"${ROLLNW_RELEASE_TAG}\",\"snapshot\":\"${snapshot}\"}")
        string(JSON build_identity SET "${build_identity}" tools "${tool_name}" "${tool_build_info}")
        string(REPLACE "." ";" components "${base_version}")
        list(GET components 0 version_major)
        list(GET components 1 version_minor)
        list(GET components 2 version_patch)
        configure_file("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/tool_version.hpp.in"
            "${ROLLNW_IDENTITY_DIR}/${tool_name}/rollnw_tool_version.hpp" @ONLY)
        configure_file("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/tool_version.rc.in"
            "${ROLLNW_IDENTITY_DIR}/${tool_name}/tool_version.rc" @ONLY)
    endforeach()
    file(READ "${ROLLNW_SOURCE_DIR}/tools/vscode-smalls/package.json" extension)
    string(JSON extension_version GET "${extension}" version)
    rollnw_check_numeric_version("${extension_version}")
    string(JSON build_identity SET "${build_identity}" extension_version "\"${extension_version}\"")
    # file(CONFIGURE), like configure_file, preserves mtime when bytes match.
    file(CONFIGURE OUTPUT "${ROLLNW_IDENTITY_DIR}/build-identity.json" CONTENT "${build_identity}\n" @ONLY)
endfunction()

if(CMAKE_SCRIPT_MODE_FILE STREQUAL CMAKE_CURRENT_LIST_FILE)
    if(NOT DEFINED ROLLNW_RELEASE_TAG)
        set(ROLLNW_RELEASE_TAG "")
    endif()
    rollnw_generate_tool_versions()
endif()
