include("${CMAKE_CURRENT_LIST_DIR}/BuildIdentity.cmake")
set(ROLLNW_TOOL_VERSION_DIR "${PROJECT_BINARY_DIR}/tool_versions")
set(ROLLNW_SOURCE_DIR "${PROJECT_SOURCE_DIR}")
set(ROLLNW_IDENTITY_DIR "${ROLLNW_TOOL_VERSION_DIR}")
set(ROLLNW_RELEASE_TAG "" CACHE STRING "Explicit approved release tag; empty means development")

if(WIN32 AND PROJECT_IS_TOP_LEVEL AND (ROLLNW_BUILD_TOOLS OR ROLLNW_BUILD_RENDERER))
    enable_language(RC)
endif()

# Refresh once per build: commits and dirty-state changes must not leave stale
# identity. Unchanged generated bytes retain their mtime.
rollnw_generate_tool_versions()
set(identity_outputs "${ROLLNW_TOOL_VERSION_DIR}/build-identity.json")
foreach(tool IN LISTS ROLLNW_VERSIONED_TOOLS)
    list(APPEND identity_outputs "${ROLLNW_TOOL_VERSION_DIR}/${tool}/rollnw_tool_version.hpp"
        "${ROLLNW_TOOL_VERSION_DIR}/${tool}/tool_version.rc")
endforeach()
add_custom_target(rollnw-tool-versions
    COMMAND ${CMAKE_COMMAND}
        "-DROLLNW_SOURCE_DIR=${PROJECT_SOURCE_DIR}"
        "-DROLLNW_IDENTITY_DIR=${ROLLNW_TOOL_VERSION_DIR}"
        "-DROLLNW_RELEASE_TAG=${ROLLNW_RELEASE_TAG}"
        -P "${CMAKE_CURRENT_LIST_DIR}/BuildIdentity.cmake"
    BYPRODUCTS ${identity_outputs}
    COMMENT "Checking tool build identity"
    VERBATIM)

# Each call attaches metadata to one executable target, a CMake singleton.
function(rollnw_use_tool_version target)
    add_dependencies(${target} rollnw-tool-versions)
    target_include_directories(${target} PRIVATE "${ROLLNW_TOOL_VERSION_DIR}/${target}")
    if(WIN32)
        target_sources(${target} PRIVATE "${ROLLNW_TOOL_VERSION_DIR}/${target}/tool_version.rc")
    endif()
endfunction()

# Register after enable_testing() and after all executable targets exist.
function(rollnw_add_tool_version_tests)
    add_test(NAME build-identity
        COMMAND ${CMAKE_COMMAND} "-DSOURCE_DIR=${PROJECT_SOURCE_DIR}"
            "-DTEST_ROOT=${PROJECT_BINARY_DIR}/build-identity-tests"
            -P "${PROJECT_SOURCE_DIR}/tests/build_identity.cmake")
    foreach(target IN LISTS ROLLNW_VERSIONED_TOOLS)
        if(NOT TARGET ${target})
            continue()
        endif()
        add_test(NAME ${target}-version
            COMMAND ${CMAKE_COMMAND}
                "-DTOOL=$<TARGET_FILE:${target}>"
                "-DHEADER=${ROLLNW_TOOL_VERSION_DIR}/${target}/rollnw_tool_version.hpp"
                -P "${PROJECT_SOURCE_DIR}/tests/tool_version.cmake")
    endforeach()
endfunction()

if(PROJECT_IS_TOP_LEVEL AND (ROLLNW_BUILD_TOOLS OR ROLLNW_BUILD_RENDERER))
    install(FILES "${ROLLNW_TOOL_VERSION_DIR}/build-identity.json" DESTINATION .)
endif()
